# Generated by Django 4.2 on 2026-04-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='apariconia',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram'), ('Referido', 'Referido'), ('Boletas', 'Boleta'), ('Amigo', 'Amigo'), ('otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_curso',
            field=models.CharField(choices=[('curso_completo', 'Completo'), ('Reforzamiento', 'Reforzamiento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_pago',
            field=models.CharField(choices=[('pago_completo', 'Completo'), ('Anticipo', 'Anticipo'), ('Beneficio', 'Beneficio')], max_length=50),
        ),
    ]
