# Generated by Django 4.2 on 2026-04-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0002_alter_matricula_apariconia_alter_matricula_sexo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=50, unique=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('anticipo', 'Anticipo')], max_length=20)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escuela.matricula')),
            ],
        ),
    ]
