# Generated by Django 4.2 on 2026-04-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0004_remove_instructor_usuario_matricula_estado_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=6500, max_digits=10),
        ),
    ]
