# Generated by Django 4.2 on 2026-04-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0005_matricula_monto_pagado_alter_matricula_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_pago',
            field=models.CharField(choices=[('pago_completo', 'Pago Completo'), ('Anticipo', 'Anticipo'), ('Beneficio', 'Beneficio')], max_length=50),
        ),
    ]
